### ISSUE TITLE
run.sh is not executable by default

### ISSUE THREAD

**Issue by lx6g** [sodelalbert/Withings2Garmin#1]
Default installation does not mark run.sh as executable, therefore crontab jobs fail with "/home/pi/Withings2Garmin/run.sh: Permission denied"

As is:
-rw-r--r-- 1 pi pi   113 Jan 30 23:20 run.sh

Fix:
chmod +x run.sh
-rwxr-xr-x 1 pi pi   113 Jan 30 23:20 run.sh

**Comment by sodelalbert** [comment]
Thank you for report. I will add it to Readme.md.
